#pragma once

#include <string>

enum class EPredictStatus
{
    Pending,
    WinnerPredicted,
    ScorePredicted,
    Failed,
    Missed
};

enum class ETeam
{
    PremierLeagueStart = 1,
    AFCBournemouth = 1,
    Arsenal,
    AstonVilla,
    Brentford,
    BrightonAndHoveAlbion,
    Chelsea,
    CrystalPalace,
    Everton,
    Fulham,
    IpswichTown,
    LeicesterCity,
    Liverpool,
    ManchesterCity,
    ManchesterUnited,
    NewcastleUnited,
    NottinghamForest,
    Southampton,
    TottenhamHotspur,
    WestHamUnited,
    Wolverhampton,
    PremierLeagueEnd = Wolverhampton,

    LaLigaStart = PremierLeagueEnd + 1,
    Alaves = LaLigaStart,
    AthleticClub,
    AtleticoMadrid,
    Barcelona,
    CeltaVigo,
    Espanyol,
    Getafe,
    Girona,
    LasPalmas,
    Leganes,
    Mallorca,
    Osasuna,
    RayoVallecano,
    RealBetis,
    RealMadrid,
    RealSociedad,
    RealValladolid,
    Sevilla,
    Valencia,
    Villarreal,
    LaLigaEnd = Villarreal,

    // SerieA
    SerieAStart = LaLigaEnd + 1,
    ACMilan = SerieAStart,
    Atalanta,
    Bologna,
    Cagliari,
    Como,
    Empoli,
    Fiorentina,
    Genoa,
    InterMilan,
    Juventus,
    Lazio,
    Lecce,
    Monza,
    Napoli,
    Parma,
    Roma,
    Torino,
    Udinese,
    Venezia,
    Verona,
    SerieAEnd = Verona,

    BundesligaStart = SerieAEnd + 1,
    Augsburg = BundesligaStart,
    BayerLeverkusen,
    BayernMunich,
    Bochum,
    BorussiaDortmund,
    BorussiaMgladbach,
    EintrachtFrankfurt,
    Freiburg,
    Heidenheim,
    Hoffenheim,
    HolsteinKiel,
    Mainz,
    RBLeipzig,
    StPauli,
    Stuttgart,
    UnionBerlin,
    WerderBremen,
    Wolfsburg,
    BundesligaEnd = Wolfsburg,

    Ligue1Start = BundesligaEnd + 1,
    Angers = Ligue1Start,
    Auxerre,
    Brest,
    LeHavre,
    Lens,
    Lille,
    Lyon,
    Marseille,
    Monaco,
    Montpellier,
    Nantes,
    Nice,
    PSG,
    Reims,
    Rennes,
    SaintEtienne,
    Strasbourg,
    Toulouse,
    Ligue1End = Toulouse,

    Benfica,
    Celtic,
    ClubBrugge,
    DinamoZagreb,
    FKCrvenaZvezda,
    Feyenoord,
    PSV,
    Salzburg,
    ShakhtarDonetsk,
    SlovanBratislava,
    SpartaPrague,
    SportingLisbon,
    SturmGraz,
    YoungBoys,

    // New Teams
    Sampdoria,
    Sassuolo1,
    Cesena,

    // Club World Cup
    AlAhly,
    AlAin,
    AlHilal,
    AucklandCity,
    BocaJuniors,
    Botafogo,
    Esperance,
    Flamengo,
    Fluminense,
    InterMiami,
    MamelodiSundowns,
    Monterrey,
    Pachuca,
    Palmerias,
    Porto,
    RiverPlate,
    SeatleSounders,
    Ulsan,
    UrawaReds,
    Wydad,
    LosAngelesFC,

    // Laliga 2025
    LaLiga2025Start,
    Levante = LaLiga2025Start,
    Oviedo,
    Elche,
    LaLiga2025End = Elche,

    // Premier League 2025
    PremierLeague2025Start,
    Burnley = PremierLeague2025Start,
    Leeds,
    Sunderland,
    PremierLeague2025End = Sunderland,

    // Serie A 2025
    SerieA2025Start,
    Cremonese = SerieA2025Start,
    Pisa,
    Sassuolo,
    SerieA2025End = Sassuolo,

    // Bundesliga 2025
    Bundesliga2025Start,
    Koln = Bundesliga2025Start,
    Hamburg,
    Bundesliga2025End = Hamburg,

    // Ligue 1 2025
    Ligue12025Start,
    Lorient = Ligue12025Start,
    Metz,
    ParisFC,
    Ligue12025End = ParisFC,

    // International
    // Nations League
    NationsLeagueStart = 10000,
    Portugal = NationsLeagueStart,
    Croatia,
    Poland,
    Scotland,
    Italy,
    France,
    Belgium,
    Israel,
    Germany,
    Netherlands,
    BosniaAndHerzegovina,
    Hungary,
    Denmark,
    Spain,
    Serbia,
    Switzerland,
    Georgia,
    Albania,
    Czechia,
    Ukraine,
    Greece,
    England,
    RepublicOfIreland,
    Finland,
    Slovenia,
    Norway,
    Austria,
    Kazakhstan,
    Turkiye,
    Wales,
    Iceland,
    Montenegro,
    Sweden,
    Slovakia,
    Azerbaijan,
    Estonia,
    Romania,
    Kosovo,
    Cyprus,
    Lithuania,
    Belarus,
    Bulgaria,
    NorthernIreland,
    Luxemburg,
    NorthMacedonia,
    Armenia,
    Latvia,
    FaroeIslands,
    SanMarino,
    Gibraltar,
    Liechtenstein,
    Moldova,
    Malta,
    Andorra,
    NationsLeagueEnd = Andorra
};

class Team
{
public:
    static std::string ToString(ETeam team);
    static std::string ToShortString(ETeam team);
};
